# Generated by Django 5.2.4 on 2025-10-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_custom_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stream_priority',
            field=models.IntegerField(default=0, help_text='Priority level for streaming tasks. Lower values indicate higher priority.'),
        ),
    ]
