# Generated by Django 5.1.6 on 2025-03-01 14:10

from django.db import migrations
from django.utils.text import slugify


def add_dvr_templates(apps, schema_editor):
    CoreSettings = apps.get_model("core", "CoreSettings")

    defaults = [
        (slugify("DVR TV Template"), "DVR TV Template", "TV_Shows/{show}/S{season:02d}E{episode:02d}.mkv"),
        (slugify("DVR Movie Template"), "DVR Movie Template", "Movies/{title} ({year}).mkv"),
    ]

    for key, name, value in defaults:
        CoreSettings.objects.get_or_create(key=key, defaults={"name": name, "value": value})


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_default_proxy_settings"),
    ]

    operations = [
        migrations.RunPython(add_dvr_templates),
    ]
