# Generated for the current Dispatcharr schema.
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("m3u", "0019_m3uaccountprofile_exp_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaLibraryExportTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("target_type", models.CharField(choices=[("jellyfin", "Jellyfin"), ("emby", "Emby")], default="jellyfin", max_length=16)),
                ("enabled", models.BooleanField(default=True)),
                ("output_root", models.TextField(unique=True)),
                ("playback_base_url", models.URLField(max_length=1000)),
                ("playback_cidrs", models.TextField(help_text="Comma-separated CIDRs allowed to use this target's STRM URLs.")),
                ("playback_stream_limit", models.PositiveIntegerField(default=0, help_text="Maximum concurrent streams for this target; zero is unlimited.")),
                ("include_nfo", models.BooleanField(default=True)),
                ("auto_export_on_vod_change", models.BooleanField(default=True)),
                ("last_exported_at", models.DateTimeField(blank=True, null=True)),
                ("last_export_status", models.CharField(choices=[("idle", "Idle"), ("running", "Running"), ("success", "Success"), ("error", "Error")], default="idle", max_length=16)),
                ("last_export_message", models.TextField(blank=True, default="")),
                ("last_export_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="MediaLibrarySource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("provider_type", models.CharField(choices=[("plex", "Plex"), ("emby", "Emby"), ("jellyfin", "Jellyfin"), ("local", "Local")], max_length=32)),
                ("base_url", models.URLField(blank=True, default="", max_length=1000)),
                ("api_token", models.CharField(blank=True, default="", max_length=1024)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("password", models.CharField(blank=True, default="", max_length=255)),
                ("verify_ssl", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=True)),
                ("add_to_vod", models.BooleanField(default=True)),
                ("sync_interval", models.PositiveIntegerField(default=0, help_text="Automatic synchronization interval in hours; zero disables it.")),
                ("include_libraries", models.JSONField(blank=True, default=list)),
                ("library_content_types", models.JSONField(blank=True, default=dict, help_text="Optional per-library media type overrides keyed by provider library ID.")),
                ("provider_config", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(choices=[("idle", "Idle"), ("running", "Running"), ("success", "Success"), ("error", "Error")], default="idle", max_length=16)),
                ("last_sync_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media_library_sources", to="django_celery_beat.periodictask")),
                ("vod_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media_library_sources", to="m3u.m3uaccount")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="MediaLibraryLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("path", models.TextField()),
                ("content_type", models.CharField(choices=[("movie", "Movies"), ("series", "Series"), ("mixed", "Movies and series")], default="mixed", max_length=16)),
                ("include_subdirectories", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="locations", to="media_servers.medialibrarysource")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="MediaLibraryImportRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("queued", "Queued"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=16)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("stages", models.JSONField(blank=True, default=dict)),
                ("scope_results", models.JSONField(blank=True, default=dict)),
                ("processed_items", models.PositiveIntegerField(default=0)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("created_items", models.PositiveIntegerField(default=0)),
                ("updated_items", models.PositiveIntegerField(default=0)),
                ("removed_items", models.PositiveIntegerField(default=0)),
                ("skipped_items", models.PositiveIntegerField(default=0)),
                ("ambiguous_items", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                ("cancellation_requested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("integration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="import_runs", to="media_servers.medialibrarysource")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="MediaLibraryExportRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("queued", "Queued"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=16)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True, default="")),
                ("cancellation_requested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="export_runs", to="media_servers.medialibraryexporttarget")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="medialibraryexporttarget", index=models.Index(fields=["enabled", "auto_export_on_vod_change"], name="media_serve_enabled_28e257_idx")),
        migrations.AddIndex(model_name="medialibrarysource", index=models.Index(fields=["provider_type", "enabled"], name="media_serve_provide_82a7a8_idx")),
        migrations.AddConstraint(model_name="medialibrarylocation", constraint=models.UniqueConstraint(fields=("source", "path"), name="unique_media_location_path")),
        migrations.AddIndex(model_name="medialibraryimportrun", index=models.Index(fields=["integration", "created_at"], name="media_serve_integra_250357_idx")),
        migrations.AddIndex(model_name="medialibraryimportrun", index=models.Index(fields=["integration", "status"], name="media_serve_integra_7ecae3_idx")),
        migrations.AddIndex(model_name="medialibraryimportrun", index=models.Index(fields=["status", "created_at"], name="media_serve_status_d6f390_idx")),
        migrations.AddConstraint(model_name="medialibraryimportrun", constraint=models.UniqueConstraint(condition=models.Q(("status__in", ("pending", "queued", "running"))), fields=("integration",), name="one_active_media_import_per_source")),
        migrations.AddIndex(model_name="medialibraryexportrun", index=models.Index(fields=["target", "created_at"], name="media_serve_target__ee4da9_idx")),
        migrations.AddIndex(model_name="medialibraryexportrun", index=models.Index(fields=["target", "status"], name="media_serve_target__9f3e27_idx")),
        migrations.AddConstraint(model_name="medialibraryexportrun", constraint=models.UniqueConstraint(condition=models.Q(("status__in", ("pending", "queued", "running"))), fields=("target",), name="one_active_media_export_per_target")),
    ]
