# Generated by Django 5.2.11 on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('m3u', '0018_add_profile_custom_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaServerIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('provider_type', models.CharField(choices=[('plex', 'Plex'), ('emby', 'Emby'), ('jellyfin', 'Jellyfin'), ('local', 'Local')], max_length=32)),
                ('base_url', models.URLField(blank=True, default='', max_length=1000)),
                ('api_token', models.CharField(blank=True, default='', max_length=1024)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('add_to_vod', models.BooleanField(default=True)),
                ('sync_interval', models.IntegerField(default=0, help_text='Auto-sync interval in hours (0 disables scheduled sync)')),
                ('include_libraries', models.JSONField(blank=True, default=list)),
                ('provider_config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=16)),
                ('last_sync_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_server_integrations', to='django_celery_beat.periodictask')),
                ('vod_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_server_integrations', to='m3u.m3uaccount')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['provider_type', 'enabled'], name='media_serve_provide_705f2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaServerSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('stages', models.JSONField(blank=True, default=dict, null=True)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('created_items', models.PositiveIntegerField(default=0)),
                ('updated_items', models.PositiveIntegerField(default=0)),
                ('removed_items', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='media_servers.mediaserverintegration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['integration', 'created_at'], name='media_serve_integra_f47940_idx'),
                    models.Index(fields=['integration', 'status'], name='media_serve_integra_5f95b5_idx'),
                ],
            },
        ),
    ]
