# Generated by Django 6.0.4 on 2026-04-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0038_backfill_auto_created_by_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelgroupm3uaccount',
            name='auto_sync_channel_end',
            field=models.FloatField(blank=True, help_text='Optional upper bound for auto-created channel numbers in this group. Leave blank for unlimited fill. Overflow streams are skipped and reported in the completion notification.', null=True),
        ),
    ]
