# Generated by Django 6.0.5 on 2026-06-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0038_add_catchup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='catchup_provider_stream_id',
            field=models.CharField(blank=True, default='', help_text='Provider stream_id of the highest-priority catch-up stream (for timeshift URL construction)', max_length=64),
        ),
    ]
