# Generated by Django 6.0.4 on 2026-05-19 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0023_schedules_direct'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sdprogrammd5',
            name='epg_sdprogr_epg_sou_222ce1_idx',
        ),
    ]
