# Generated by Django 5.2.4 on 2025-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0016_m3uaccount_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m3uaccount',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='m3ufilter',
            name='custom_properties',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
