# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m3u", "0019_m3uaccountprofile_exp_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="servergroup",
            name="max_streams",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of concurrent streams shared across all accounts in this group (0 for unlimited)",
            ),
        ),
    ]
