# Generated by Django 6.0.4 on 2026-04-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0019_m3uaccountprofile_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='auto_cleanup_unused_channels',
            field=models.BooleanField(default=False, help_text='Automatically delete auto-created channels whose provider stream has disappeared after a refresh. Hidden channels are always preserved.'),
        ),
    ]
