# Generated by Django 5.2.4 on 2025-12-20 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("m3u", "0018_add_profile_custom_properties"),
        ("vod", "0003_vodlogo_alter_movie_logo_alter_series_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "library_type",
                    models.CharField(
                        choices=[("movies", "Movies"), ("shows", "TV Shows")],
                        max_length=20,
                    ),
                ),
                ("metadata_language", models.CharField(blank=True, default="", max_length=12)),
                ("metadata_country", models.CharField(blank=True, default="", max_length=12)),
                ("metadata_options", models.JSONField(blank=True, default=dict, null=True)),
                ("scan_interval_minutes", models.PositiveIntegerField(default=1440)),
                ("auto_scan_enabled", models.BooleanField(default=True)),
                ("add_to_vod", models.BooleanField(default=False)),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_scan_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vod_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_libraries",
                        to="m3u.m3uaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("show", "Show"),
                            ("episode", "Episode"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("sort_title", models.CharField(blank=True, default="", max_length=512)),
                ("normalized_title", models.CharField(blank=True, default="", max_length=512)),
                ("synopsis", models.TextField(blank=True, default="")),
                ("tagline", models.TextField(blank=True, default="")),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("rating", models.CharField(blank=True, default="", max_length=10)),
                ("runtime_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("season_number", models.IntegerField(blank=True, null=True)),
                ("episode_number", models.IntegerField(blank=True, null=True)),
                ("genres", models.JSONField(blank=True, default=list, null=True)),
                ("tags", models.JSONField(blank=True, default=list, null=True)),
                ("studios", models.JSONField(blank=True, default=list, null=True)),
                ("cast", models.JSONField(blank=True, default=list, null=True)),
                ("crew", models.JSONField(blank=True, default=list, null=True)),
                ("poster_url", models.TextField(blank=True, default="")),
                ("backdrop_url", models.TextField(blank=True, default="")),
                ("movie_db_id", models.CharField(blank=True, default="", max_length=64)),
                ("imdb_id", models.CharField(blank=True, default="", max_length=32)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("metadata_source", models.CharField(blank=True, default="", max_length=32)),
                ("metadata_last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("first_imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="media_library.library",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="media_library.mediaitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_title", "title"],
            },
        ),
        migrations.CreateModel(
            name="LibraryLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=1024)),
                ("include_subdirectories", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="media_library.library",
                    ),
                ),
            ],
            options={
                "unique_together": {("library", "path")},
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=1024)),
                ("relative_path", models.CharField(blank=True, default="", max_length=1024)),
                ("file_name", models.CharField(max_length=512)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="media_library.library",
                    ),
                ),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="media_library.mediaitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("library", "path")},
            },
        ),
        migrations.CreateModel(
            name="MediaItemVODLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vod_link",
                        to="media_library.mediaitem",
                    ),
                ),
                (
                    "vod_episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_library_links",
                        to="vod.episode",
                    ),
                ),
                (
                    "vod_movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_library_links",
                        to="vod.movie",
                    ),
                ),
                (
                    "vod_series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_library_links",
                        to="vod.series",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtworkAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_type", models.CharField(choices=[("poster", "Poster"), ("backdrop", "Backdrop")], max_length=16)),
                ("source", models.CharField(blank=True, default="", max_length=32)),
                ("external_url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artwork_assets",
                        to="media_library.mediaitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WatchProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position_ms", models.PositiveBigIntegerField(default=0)),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("last_watched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progress_entries",
                        to="media_library.mediafile",
                    ),
                ),
                (
                    "media_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="media_library.mediaitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "media_item")},
            },
        ),
        migrations.CreateModel(
            name="LibraryScan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scan_type",
                    models.CharField(
                        choices=[("quick", "Quick"), ("full", "Full")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                ("stages", models.JSONField(blank=True, default=dict, null=True)),
                ("processed_files", models.PositiveIntegerField(default=0)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("new_files", models.PositiveIntegerField(default=0)),
                ("updated_files", models.PositiveIntegerField(default=0)),
                ("removed_files", models.PositiveIntegerField(default=0)),
                ("unmatched_files", models.PositiveIntegerField(default=0)),
                ("log", models.TextField(blank=True, default="")),
                ("extra", models.JSONField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="media_library.library",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="librarylocation",
            index=models.Index(fields=["library", "is_primary"], name="media_libr_library_b13f17_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(fields=["library", "item_type"], name="media_libr_library_a7ec3e_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(fields=["library", "sort_title"], name="media_libr_library_2dc3a5_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(fields=["library", "updated_at"], name="media_libr_library_0f7e9b_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(fields=["parent", "season_number", "episode_number"], name="media_libr_parent__f58b2b_idx"),
        ),
        migrations.AddConstraint(
            model_name="mediaitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(item_type="episode"),
                fields=("parent", "season_number", "episode_number"),
                name="unique_episode_per_season",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(fields=["media_item"], name="media_libr_media_i_4bf7b4_idx"),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(fields=["library", "is_primary"], name="media_libr_library_0b3ae5_idx"),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(fields=["library", "last_seen_at"], name="media_libr_library_31c4a1_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaitemvodlink",
            index=models.Index(fields=["media_item"], name="media_libr_media_i_f9b327_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaitemvodlink",
            index=models.Index(fields=["vod_movie"], name="media_libr_vod_mo_6d43ad_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaitemvodlink",
            index=models.Index(fields=["vod_series"], name="media_libr_vod_se_05e51a_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaitemvodlink",
            index=models.Index(fields=["vod_episode"], name="media_libr_vod_ep_c0b0c7_idx"),
        ),
        migrations.AddIndex(
            model_name="artworkasset",
            index=models.Index(fields=["media_item", "asset_type"], name="media_libr_media_i_6fe152_idx"),
        ),
        migrations.AddIndex(
            model_name="watchprogress",
            index=models.Index(fields=["user", "media_item"], name="media_libr_user_id_5f9dd5_idx"),
        ),
        migrations.AddIndex(
            model_name="libraryscan",
            index=models.Index(fields=["library", "created_at"], name="media_libr_library_1f1b2e_idx"),
        ),
        migrations.AddIndex(
            model_name="libraryscan",
            index=models.Index(fields=["library", "status"], name="media_libr_library_0f3a70_idx"),
        ),
    ]
