# Generated by Django 5.0.14 on 2025-09-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryscan',
            name='processed_files',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
