# Generated by Django 5.0.14 on 2025-10-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_library_use_as_vod_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='requires_transcode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='transcode_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='transcode_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='transcoded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='transcoded_mime_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='transcoded_path',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
